version: 2
jobs:
  build:
    branch: circleci
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout

      # Install and cache libmtbl
      - restore_cache:
          key: libmtbl-v2
      - run: |
          if test -d /mnt/libs ; then
            cp /mnt/libs/* /usr/lib/x86_64-linux-gnu/ ;
          else
            mkdir /mnt/libs ;
            apt update ;
            apt install -y libmtbl-dev ;
            cp /usr/lib/x86_64-linux-gnu/lib{mtbl,snappy}* /mnt/libs/ ;
          fi
      - save_cache:
          key: libmtbl-v2
          paths:
            - /mnt/libs
      - run:
          name: Check libs
          command: ls -lh /usr/lib/x86_64-linux-gnu/libmtbl*

      # Update and cache cargo deps
      - restore_cache:
          key: cargo-v2-{{ checksum "Cargo.toml" }}
      - run: cargo update
      - run: cargo fetch
      - save_cache:
          key: cargo-v2-{{ checksum "Cargo.toml" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git

      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Test
          command: cargo test --verbose
